name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  trigger-project-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Project B workflow_dispatch
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITTOKEN }}
          repository: lenkie-code/test-automation
          workflow: accept-test-data.yml   # <-- This should match the workflow filename in Project B
          ref: main                       # <-- Or the branch you want to run it on
          inputs: |
            test_email: "sampleuser@lenkie.com"
            test_amount: "2500"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project..
