#development repository
name: trigger tests in another repository
on: workflow_dispatch
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITTOKEN }}
          repository: lenkie-code/test-automation
          event-type: my-event
          client-payload: '{"github": ${{ toJSON(github) }}}'
